.gitignore
CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/MaterialInfoController.java
CNR_FURNITURE/src/main/webapp/WEB-INF/views/standardInfo/materialInfo.jsp

240404 hyunju01: materialInfo.jsp, MaterialInfoController 추가

240404 hyunju01: materialInfo.jsp, MaterialInfoController 추가

---

CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/MaterialInfoController.java
CNR_FURNITURE/src/main/webapp/WEB-INF/views/includes/header.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/main/index.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/standardInfo/materialInfo.jsp

240404 hyunju01: materialInfo.css, 모달추가

240404 hyunju01: materialInfo.css, 모달추가

---

CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/MaterialMNGController.java
CNR_FURNITURE/src/main/resources/static/css/materialIB.css
CNR_FURNITURE/src/main/webapp/WEB-INF/views/materialManagement/materialIB.jsp

240404 suha02: 자재입고조회Controller, jsp, css 생성

240404 suha02: 자재입고조회Controller, jsp, css 생성

---

CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/ProcessController.java
CNR_FURNITURE/src/main/resources/static/css/instruction.css
CNR_FURNITURE/src/main/webapp/WEB-INF/views/process/instruction.jsp

240404 dahye04 : 제조지시 css, jsp, controller

240404 dahye04 : 제조지시 css, jsp, controller

---

CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/MaterialMNGController.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/MaterialMNGVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/utils/Constants.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/utils/UtilDateTime.java
CNR_FURNITURE/src/main/resources/mybatis/mapper/MaterialMNGMapper.xml
CNR_FURNITURE/src/main/resources/static/css/materialIB.css
CNR_FURNITURE/src/main/resources/static/js/materialIB.js
CNR_FURNITURE/src/main/webapp/WEB-INF/views/materialManagement/materialIB.jsp

240405 suha05: 자재입고조회 jsp, css, js 수정/날짜 검색관련 utils생성, MaterialMNG의 controller, xml, vo 작성

240405 suha05: 자재입고조회 jsp, css, js 수정/날짜 검색관련 utils생성, MaterialMNG의 controller, xml, vo 작성

---

CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/ProcessController.java
CNR_FURNITURE/src/main/resources/static/css/instruction.css
CNR_FURNITURE/src/main/webapp/WEB-INF/views/process/instructionPlan.jsp

240405 dahye06 : 제조지시 프론트 완성, 제조지시수행 파일 생성

240405 dahye06 : 제조지시 프론트 완성, 제조지시수행 파일 생성

---

CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/BomController.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/ItemInfoController.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/MaterialInfoController.java
CNR_FURNITURE/src/main/resources/static/css/bomInfo.css
CNR_FURNITURE/src/main/resources/static/css/materialInfo.css
CNR_FURNITURE/src/main/webapp/WEB-INF/views/standardInfo/bomInfo.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/standardInfo/itemInfo.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/standardInfo/materialInfo.jsp

240405 hyunju04: item, material, bom jsp & css

240405 hyunju04: item, material, bom jsp & css

---

CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/WorkController.java
CNR_FURNITURE/src/main/resources/static/css/qualityInspection.css
CNR_FURNITURE/src/main/resources/static/css/work.css
CNR_FURNITURE/src/main/webapp/WEB-INF/views/includes/header.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/work/work.jsp

240405 jihyeon04 header.jsp 수정

240405 jihyeon04 header.jsp 수정

---

CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/ItemInfoController.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/ItemInfoVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/mapper/ItemInfoMapper.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/ItemInfoService.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/ItemInfoServiceImpl.java
CNR_FURNITURE/src/main/resources/mybatis/mapper/ItemInfoMapper.xml
CNR_FURNITURE/src/main/resources/static/css/materialInfo.css
CNR_FURNITURE/src/main/webapp/WEB-INF/views/standardInfo/itemInfo.jsp

240405 hyunju04: item crud

---

CNR_FURNITURE/src/main/resources/static/css/main.css
CNR_FURNITURE/src/main/resources/static/css/table.css
CNR_FURNITURE/src/main/resources/static/css/work.css
CNR_FURNITURE/src/main/webapp/WEB-INF/views/includes/header.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/work/work.jsp

240406 jihyeon04 header.jsp 수정

240406 jihyeon04 header.jsp 수정

---

CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/ItemInfoController.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/ItemInfo/ItemInfoSearch.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/ItemInfo/ItemInfoVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/mapper/ItemInfoMapper.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/ItemInfoService.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/ItemInfoServiceImpl.java
CNR_FURNITURE/src/main/resources/mybatis/mapper/ItemInfoMapper.xml
CNR_FURNITURE/src/main/resources/static/js/itemInfo.js
CNR_FURNITURE/src/main/webapp/WEB-INF/views/standardInfo/itemInfo.jsp

240406 hyunju06: item js & mapper

240406 hyunju06: item js & mapper

---

CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/MaterialMNGController.java
CNR_FURNITURE/src/main/resources/static/css/materialMNG.css
CNR_FURNITURE/src/main/resources/static/js/materialMNG.js
CNR_FURNITURE/src/main/webapp/WEB-INF/views/materialManagement/materialIB.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/materialManagement/materialInventory.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/materialManagement/materialOB.jsp

240406 suha10: 자재IB조회/자재OB조회 jsp, css, js 완료, 자재재고jsp 생성

240406 suha10: 자재IB조회/자재OB조회 jsp, css, js 완료, 자재재고jsp 생성

---

CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/ProcessController.java
CNR_FURNITURE/src/main/resources/static/css/process.css
CNR_FURNITURE/src/main/webapp/WEB-INF/views/process/processInfo.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/process/processMain.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/process/processPlan.jsp

240406 dahye09 : 제조지시 프론트, 제조수행 프론트 완성, 공정관리 프론트 작업, 파일 이름 변경

240406 dahye09 : 제조지시 프론트, 제조수행 프론트 완성, 공정관리 프론트 작업, 파일 이름 변경

---

CNR_FURNITURE/src/main/resources/static/css/table.css
CNR_FURNITURE/src/main/resources/static/css/work.css
CNR_FURNITURE/src/main/webapp/WEB-INF/views/work/work.jsp

240407 jihyeon08 work.jsp 수정, table.css height 고정크기 삭제

240407 jihyeon08 work.jsp 수정, table.css height 고정크기 삭제

---

CNR_FURNITURE/src/main/resources/static/css/itemMNG.css
CNR_FURNITURE/src/main/resources/static/js/itemMNG.js
CNR_FURNITURE/src/main/webapp/WEB-INF/views/itemManagement/itemFinishedOB.jsp

240408 suha14 : material 프론트 완료, itemIB 완료, itemSemiOB완료, itemFinishedOB 진행중

240408 suha14 : material 프론트 완료, itemIB 완료, itemSemiOB완료, itemFinishedOB 진행중

---

CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/MaterialInfoController.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/MaterialInfo/MaterialInfoSearch.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/MaterialInfo/MaterialInfoVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/MaterialInfoVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/mapper/MaterialInfoMapper.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/MaterialInfoService.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/MaterialInfoServiceImpl.java
CNR_FURNITURE/src/main/resources/mybatis/mapper/ItemInfoMapper.xml
CNR_FURNITURE/src/main/resources/mybatis/mapper/MaterialInfoMapper.xml
CNR_FURNITURE/src/main/resources/static/css/itemInfo.css
CNR_FURNITURE/src/main/resources/static/js/itemInfo.js
CNR_FURNITURE/src/main/webapp/WEB-INF/views/standardInfo/bom.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/standardInfo/itemInfo.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/standardInfo/materialInfo.jsp

240408 hyunju07: 제품 자재관리 cru 완료

240408 hyunju07: 제품 자재관리 cru 완료

---

CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/WorkController.java
CNR_FURNITURE/src/main/resources/static/css/table.css
CNR_FURNITURE/src/main/resources/static/css/work.css
CNR_FURNITURE/src/main/resources/static/js/work.js
CNR_FURNITURE/src/main/webapp/WEB-INF/views/work/todayWorkInsert.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/work/work.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/work/workerInsert.jsp

240408 jihyeon02 work, todayWorkInsert

240408 jihyeon02 work, todayWorkInsert

---

CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/ItemMNGController.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/QualityController.java
CNR_FURNITURE/src/main/resources/static/css/itemMNG.css
CNR_FURNITURE/src/main/resources/static/css/materialMNG.css
CNR_FURNITURE/src/main/resources/static/css/quality.css
CNR_FURNITURE/src/main/resources/static/js/itemMNG.js
CNR_FURNITURE/src/main/webapp/WEB-INF/views/itemManagement/itemContractInfo.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/itemManagement/itemFinishedOB.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/itemManagement/itemIB.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/itemManagement/itemInventory.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/qualityInspection/IBInspection.jsp

240408 suha01: 자재/제품/품질 jsp, css, js

240408 suha01: 자재/제품/품질 jsp, css, js

---

CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/BomController.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/BomVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/ItemInfo/ItemInfoSearch.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/ItemInfo/ItemInfoVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/bom/BomSearch.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/bom/BomVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/mapper/BomMapper.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/BomService.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/BomServiceImpl.java
CNR_FURNITURE/src/main/resources/mybatis/mapper/BomMapper.xml
CNR_FURNITURE/src/main/resources/static/css/bom.css
CNR_FURNITURE/src/main/resources/static/css/itemInfo.css
CNR_FURNITURE/src/main/resources/static/css/materialInfo.css
CNR_FURNITURE/src/main/webapp/WEB-INF/views/standardInfo/bom.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/standardInfo/bomInsert.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/standardInfo/itemInfo.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/standardInfo/materialInfo.jsp

240409 hyunju09: bom 기본페이지 완료 bomInsert 시작

240409 hyunju09: bom 기본페이지 완료 bomInsert 시작

---

CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/MachineInfoController.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/MachineMNGController.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/Machine/MachineAddVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/Machine/MachineCheckVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/Machine/SearhMachine.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/mapper/MachineInfoMapper.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/mapper/MachineMNGMapper.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/machine/MachineInfoService.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/machine/MachineInfoServiceImpl.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/machine/MachineMNGService.java
CNR_FURNITURE/src/main/resources/mybatis/mapper/MachineInfoMapper.xml
CNR_FURNITURE/src/main/resources/mybatis/mapper/MachineMNGMapper.xml
CNR_FURNITURE/src/main/resources/static/css/machine.css
CNR_FURNITURE/src/main/webapp/WEB-INF/views/machine/machineCheck.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/machine/machineCheckInfo.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/machine/machineInfo.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/machine/machineManagement.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/machine/machineOperationStatus.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/machine/machineRepair.jsp

240409 daeun08 machine css

---

CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/BomController.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/mapper/BomMapper.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/BomService.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/BomServiceImpl.java
CNR_FURNITURE/src/main/resources/mybatis/mapper/BomMapper.xml
CNR_FURNITURE/src/main/webapp/WEB-INF/views/standardInfo/bom.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/standardInfo/bomInsert.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/standardInfo/materialInfo.jsp

240410 hyunju09: bom관리&등록 조회

---

CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/ProcessController.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/process/ProcessCtVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/process/ProcessDate.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/process/ProcessInfoVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/process/ProcessItemVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/process/ProcessVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/mapper/ProcessMapper.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/ProcessService.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/ProcessServiceImpl.java
CNR_FURNITURE/src/main/resources/mybatis/mapper/ProcessMapper.xml
CNR_FURNITURE/src/main/resources/static/css/process.css
CNR_FURNITURE/src/main/webapp/WEB-INF/views/process/manufacturingInstruction.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/process/manufacturingPerform.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/process/processInfo.jsp

2024-04-10: dahye11 css 수정, 제조지시 검색기능 추가

2024-04-10: dahye11 css 수정, 제조지시 검색기능 추가

---

CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/QualityController.java
CNR_FURNITURE/src/main/resources/static/css/itemMNG.css
CNR_FURNITURE/src/main/resources/static/css/materialMNG.css
CNR_FURNITURE/src/main/resources/static/css/quality/defectiveItem.css
CNR_FURNITURE/src/main/resources/static/css/quality/defectiveProcess.css
CNR_FURNITURE/src/main/resources/static/css/quality/quality.css
CNR_FURNITURE/src/main/resources/static/css/quality/stickyOnTable.css
CNR_FURNITURE/src/main/resources/static/js/materialMNG.js
CNR_FURNITURE/src/main/resources/static/js/quality/quality.js
CNR_FURNITURE/src/main/resources/static/js/quality/stickyOnTable.js
CNR_FURNITURE/src/main/webapp/WEB-INF/views/itemManagement/itemIB.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/materialManagement/materialIB.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/materialManagement/materialOB.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/qualityInspection/defectiveItem.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/qualityInspection/defectiveProcess.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/qualityInspection/inspectionIB.jsp

240411 suha02(home) : 프론트 완료, 수입검사관리 백엔드 시작

240411 suha02(home) : 프론트 완료, 수입검사관리 백엔드 시작

---

CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/BomController.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/bom/BomVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/mapper/BomMapper.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/BomService.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/BomServiceImpl.java
CNR_FURNITURE/src/main/resources/mybatis/mapper/BomMapper.xml
CNR_FURNITURE/src/main/resources/static/css/bom.css
CNR_FURNITURE/src/main/webapp/WEB-INF/views/standardInfo/bom.jsp

240411 hyunju11: bom 수량수정완료

---

CNR_FURNITURE/src/main/java/com/cnr_furniture/config/auth/CustomAuthFailureHandler.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/config/auth/SecPrincipalDetails.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/config/auth/SecPrincipalDetailsService.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/CompanyController.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/ContractController.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/MemberController.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/CompanyVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/contract/ContractVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/member/MemberSearch.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/member/MemberVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/mapper/CompanyMapper.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/mapper/MemberMapper.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/CompanyService.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/CompanyServiceImpl.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/MemberService.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/MemberServiceImpl.java
CNR_FURNITURE/src/main/resources/mybatis/mapper/CompanyMapper.xml
CNR_FURNITURE/src/main/resources/mybatis/mapper/MemberMapper.xml
CNR_FURNITURE/src/main/resources/static/css/member.css
CNR_FURNITURE/src/main/webapp/WEB-INF/views/member/addMemberModal.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/member/login.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/member/pwChange.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/standardInfo/companyInfo.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/standardInfo/contractInfo.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/standardInfo/memberInfo.jsp

240411 siyeon05: 로그인완료, 사원정보조회, 권한관리, 계약관리, 거리처관리 프론트까지 완료

240411 siyeon05: 로그인완료, 사원정보조회, 권한관리, 계약관리, 거리처관리 프론트까지 완료

---

CNR_FURNITURE/src/main/java/com/cnr_furniture/config/SecurityConfig.java
CNR_FURNITURE/src/main/resources/application.properties

240411 siyeon06: SecurityConfig 추가, application.properties 수정

240411 siyeon06: SecurityConfig 추가, application.properties 수정

---

CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/ProcessController.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/process/ProcessCtVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/process/ProcessDate.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/process/ProcessInfoVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/process/ProcessItemVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/process/ProcessRunVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/process/ProcessVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/mapper/ProcessMapper.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/ProcessService.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/ProcessServiceImpl.java
CNR_FURNITURE/src/main/resources/mybatis/mapper/ProcessMapper.xml
CNR_FURNITURE/src/main/resources/static/css/process.css
CNR_FURNITURE/src/main/resources/static/js/process.js
CNR_FURNITURE/src/main/webapp/WEB-INF/views/process/manufacturingInstruction.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/process/manufacturingPerform.jsp

240411 dahye15 :제조 지시 검색 수정, 제조지시 등록 구현, 제조지시 모달 날짜 검색 구현

240411 dahye15 :제조 지시 검색 수정, 제조지시 등록 구현, 제조지시 모달 날짜 검색 구현

---

CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/BomController.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/bom/BomVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/mapper/BomMapper.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/BomService.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/BomServiceImpl.java
CNR_FURNITURE/src/main/resources/mybatis/mapper/BomMapper.xml
CNR_FURNITURE/src/main/resources/static/css/bom.css
CNR_FURNITURE/src/main/webapp/WEB-INF/views/standardInfo/bom.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/standardInfo/bomInsert.jsp

240412 hyunju12: bom 등록

---

CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/WorkController.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/ProcessVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/work/WorkInsertSearchVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/work/WorkProcessInfoVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/work/WorkSearchVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/work/WorkSelectCompanyVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/work/WorkSelectInstructionVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/work/WorkSelectItemVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/work/WorkSelectProcessInfoVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/work/WorkerVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/mapper/WorkMapper.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/WorkService.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/WorkServiceImpl.java
CNR_FURNITURE/src/main/resources/mybatis/mapper/WorkMapper.xml
CNR_FURNITURE/src/main/resources/static/css/main.css
CNR_FURNITURE/src/main/resources/static/css/production.css
CNR_FURNITURE/src/main/resources/static/css/work.css
CNR_FURNITURE/src/main/webapp/WEB-INF/views/includes/header.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/production/productionStatus.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/work/todayWorkInsert.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/work/work.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/work/workerInsert.jsp

240412 jihyeon01 work 제조수행정보 조회 및 검색

240412 jihyeon01 work 제조수행정보 조회 및 검색

---

CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/quality/DefectiveItemController.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/quality/DefectiveProcessController.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/quality/InspectionIBController.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/quality/InspectionOBController.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/quality/InspectionProcessController.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/quality/InspectionIBInsertVO.java
CNR_FURNITURE/src/main/resources/static/css/quality/quality.css
CNR_FURNITURE/src/main/resources/static/js/quality/inspectionIB.js
CNR_FURNITURE/src/main/webapp/WEB-INF/views/qualityInspection/inspectionIB.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/qualityInspection/inspectionProcess.jsp

240412 suha04: inspectionIB - 수입검사현황 select box option1에 따른 option2 값 구현 완료

240412 suha04: inspectionIB - 수입검사현황 select box option1에 따른 option2 값 구현 완료

---

CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/BomController.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/mapper/BomMapper.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/BomService.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/BomServiceImpl.java
CNR_FURNITURE/src/main/resources/mybatis/mapper/BomMapper.xml
CNR_FURNITURE/src/main/resources/static/css/bom.css
CNR_FURNITURE/src/main/webapp/WEB-INF/views/standardInfo/bom.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/standardInfo/bomInsert.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/standardInfo/materialInfo.jsp

240413 hyunju13: bomInsert 수정중

240413 hyunju13: bomInsert 수정중

---

CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/ProcessController.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/process/ProcessDate.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/mapper/ProcessMapper.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/ProcessService.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/ProcessServiceImpl.java
CNR_FURNITURE/src/main/resources/mybatis/mapper/ProcessMapper.xml
CNR_FURNITURE/src/main/resources/static/css/process.css
CNR_FURNITURE/src/main/resources/static/js/process.js
CNR_FURNITURE/src/main/webapp/WEB-INF/views/process/manufacturingInstruction.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/process/manufacturingPerform.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/process/processInfo.jsp

240413 dahye18 :제조 지시수행 등록 및 css 수정

240413 dahye18 :제조 지시수행 등록 및 css 수정

---

CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/BomController.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/mapper/BomMapper.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/BomService.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/BomServiceImpl.java
CNR_FURNITURE/src/main/resources/mybatis/mapper/BomMapper.xml
CNR_FURNITURE/src/main/webapp/WEB-INF/views/standardInfo/bomInsert.jsp

240413 hyunju14: bomInsert 수정화면처리중

240413 hyunju14: bomInsert 수정화면처리중

---

CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/quality/InspectionIBController.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/quality/InspectionIBInsertVO.java
CNR_FURNITURE/src/main/resources/mybatis/mapper/quality/InspectionIBMapper.xml
CNR_FURNITURE/src/main/resources/static/css/quality/quality.css
CNR_FURNITURE/src/main/resources/static/js/quality/inspectionIB.js
CNR_FURNITURE/src/main/webapp/WEB-INF/views/qualityInspection/inspectionIB.jsp

240415 suha02(home): inspectionIB 모달창 내 목록 완료. [등록] - 데이터 Controller 전달 완료. 쿼리문 보완할 것.

240415 suha02(home): inspectionIB 모달창 내 목록 완료. [등록] - 데이터 Controller 전달 완료. 쿼리문 보완할 것.

---

CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/BomController.java
CNR_FURNITURE/src/main/resources/static/css/bom.css
CNR_FURNITURE/src/main/webapp/WEB-INF/views/standardInfo/bomInsert.jsp

240415 hyunju16: bomInsert 수정후 화면처리

240415 hyunju16: bomInsert 수정후 화면처리

---

CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/ProcessController.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/mapper/ProcessMapper.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/ProcessService.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/ProcessServiceImpl.java
CNR_FURNITURE/src/main/resources/mybatis/mapper/ProcessMapper.xml
CNR_FURNITURE/src/main/resources/static/css/process.css
CNR_FURNITURE/src/main/resources/static/js/process.js
CNR_FURNITURE/src/main/webapp/WEB-INF/views/process/manufacturingPerform.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/process/processInfo.jsp

240415 dahye20 :css 조정 및, processInfo.jsp 수정

240415 dahye20 :css 조정 및, processInfo.jsp 수정

---

CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/WorkController.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/work/WorkVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/mapper/WorkMapper.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/WorkService.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/WorkServiceImpl.java
CNR_FURNITURE/src/main/resources/mybatis/mapper/WorkMapper.xml
CNR_FURNITURE/src/main/webapp/WEB-INF/views/work/work.jsp

240415 jihyeon01 work 중간커밋-작업목록, 생산실적

240415 jihyeon01 work 중간커밋-작업목록, 생산실적

---

CNR_FURNITURE/src/main/resources/static/css/bom.css
CNR_FURNITURE/src/main/resources/static/css/itemInfo.css
CNR_FURNITURE/src/main/resources/static/css/materialInfo.css
CNR_FURNITURE/src/main/webapp/WEB-INF/views/standardInfo/bomInsert.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/standardInfo/materialInfo.jsp

240416 hyunju17: bom, 자재, 제품 css 변경

240416 hyunju17: bom, 자재, 제품 css 변경

---

CNR_FURNITURE/src/main/resources/static/css/itemInfo.css
CNR_FURNITURE/src/main/resources/static/css/materialInfo.css
CNR_FURNITURE/src/main/webapp/WEB-INF/views/standardInfo/itemInfo.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/standardInfo/materialInfo.jsp

240416 hyunju18: 모달제목css수정

---

CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/MachineInfoController.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/MachineMNGController.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/Machine/MachineRepairVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/Machine/MachineWorkVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/mapper/MachineInfoMapper.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/mapper/MachineMNGMapper.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/machine/MachineInfoService.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/machine/MachineInfoServiceImpl.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/machine/MachineMNGService.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/machine/MachineMNGServiceImpl.java
CNR_FURNITURE/src/main/resources/mybatis/mapper/MachineInfoMapper.xml
CNR_FURNITURE/src/main/resources/mybatis/mapper/MachineMNGMapper.xml
CNR_FURNITURE/src/main/resources/static/css/machine.css
CNR_FURNITURE/src/main/webapp/WEB-INF/views/machine/machineCheck.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/machine/machineCheckInfo.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/machine/machineRepair.jsp

240416 daeun04 machineRepair 완료

240416 daeun04 machineRepair 완료

---

CNR_FURNITURE/src/main/java/com/cnr_furniture/service/ProcessServiceImpl.java

2024-04-16 dahye21: ProcessServiceImpl 수정

2024-04-16 dahye21: ProcessServiceImpl 수정

---

CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/quality/InspectionIBController.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/quality/InspectionProcessController.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/quality/inspectionOB/InspectionOBListVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/quality/inspectionProcess/InspectionProcessListVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/mapper/quality/InspectionProcessMapper.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/quality/inspectionProcess/InspectionProcessService.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/quality/inspectionProcess/InspectionProcessServiceImpl.java
CNR_FURNITURE/src/main/resources/mybatis/mapper/quality/InspectionIBMapper.xml
CNR_FURNITURE/src/main/resources/mybatis/mapper/quality/InspectionProcessMapper.xml
CNR_FURNITURE/src/main/resources/static/js/quality/inspectionIB.js
CNR_FURNITURE/src/main/resources/static/js/quality/inspectionProcess.js
CNR_FURNITURE/src/main/webapp/WEB-INF/views/qualityInspection/inspectionIB.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/qualityInspection/inspectionProcess.jsp

240416 suha01(home): inspectionIB(수입검사관리) - CRUD 완료, inspectionProcess(공정검사관리) - 조회 및 검색 진행중

240416 suha01(home): inspectionIB(수입검사관리) - CRUD 완료, inspectionProcess(공정검사관리) - 조회 및 검색 진행중

---

CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/ItemInfoController.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/mapper/ItemInfoMapper.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/BomService.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/BomServiceImpl.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/ItemInfoService.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/ItemInfoServiceImpl.java
CNR_FURNITURE/src/main/resources/mybatis/mapper/BomMapper.xml
CNR_FURNITURE/src/main/resources/mybatis/mapper/ItemInfoMapper.xml

240417 hyunju21: bom, item 주석

---

CNR_FURNITURE/src/main/resources/mybatis/mapper/WorkMapper.xml
CNR_FURNITURE/src/main/webapp/WEB-INF/views/work/work.jsp

240417 jihyeonHome work 완료

---

CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/MachineInfoController.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/Machine/MachineWorkVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/Machine/SearchMachineVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/mapper/MachineInfoMapper.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/machine/MachineInfoService.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/machine/MachineInfoServiceImpl.java
CNR_FURNITURE/src/main/resources/mybatis/mapper/MachineInfoMapper.xml
CNR_FURNITURE/src/main/resources/static/css/machine.css
CNR_FURNITURE/src/main/webapp/WEB-INF/views/machine/machineOperationStatus.jsp

240417 daeun06 machineOperationStatus 완료

240417 daeun06 machineOperationStatus 완료

---

CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/WorkController.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/work/todayWorkInsert/TodayWorkVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/work/todayWorkInsert/WorkProcessMachineVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/mapper/WorkMapper.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/WorkService.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/WorkServiceImpl.java
CNR_FURNITURE/src/main/resources/mybatis/mapper/WorkMapper.xml
CNR_FURNITURE/src/main/webapp/WEB-INF/views/work/todayWorkInsert.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/work/work.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/work/workerInsert.jsp

240417 jihyeonHome todayWorkInsert 중간커밋

240417 jihyeonHome todayWorkInsert 중간커밋

---

CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/MaterialInfoController.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/ProcessController.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/ScheduleController.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/scheduler/ScheduleSearch.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/scheduler/ScheduleVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/mapper/MaterialInfoMapper.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/mapper/ScheduleMapper.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/MaterialInfoService.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/MaterialInfoServiceImpl.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/ScheduleService.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/ScheduleServiceImpl.java
CNR_FURNITURE/src/main/resources/mybatis/mapper/MaterialInfoMapper.xml
CNR_FURNITURE/src/main/resources/mybatis/mapper/ScheduleMapper.xml
CNR_FURNITURE/src/main/resources/static/css/workerManagement.css
CNR_FURNITURE/src/main/webapp/WEB-INF/views/process/workerManagement.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/standardInfo/materialInfo.jsp

240417 hyunju22: schedule 조회 및 달력

240417 hyunju22: schedule 조회 및 달력

---

CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/WorkController.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/work/search/WorkSelectInsProIdVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/work/workMNG/MaterialInsertModalVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/work/workMNG/WorkVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/mapper/WorkMapper.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/WorkService.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/WorkServiceImpl.java
CNR_FURNITURE/src/main/resources/mybatis/mapper/WorkMapper.xml
CNR_FURNITURE/src/main/resources/static/css/work.css
CNR_FURNITURE/src/main/resources/static/js/work.js
CNR_FURNITURE/src/main/webapp/WEB-INF/views/work/todayWorkInsert.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/work/work.jsp

240417 jihyeon01 work 중간커밋

---

CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/ProcessController.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/process/ProcessDate.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/process/ProcessInfoVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/mapper/ProcessMapper.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/ProcessService.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/ProcessServiceImpl.java
CNR_FURNITURE/src/main/resources/mybatis/mapper/ProcessMapper.xml
CNR_FURNITURE/src/main/resources/static/css/process.css
CNR_FURNITURE/src/main/resources/static/js/process.js
CNR_FURNITURE/src/main/webapp/WEB-INF/views/process/manufacturingInstruction.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/process/processInfo.jsp

240415 dahye23 :css 조정 및, processInfo.jsp 완료

240415 dahye23 :css 조정 및, processInfo.jsp 완료

---

CNR_FURNITURE/src/main/webapp/WEB-INF/views/includes/header.jsp

240418 siyeon07: 헤더 사원정보 추가

---

CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/ScheduleController.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/scheduler/ScheduleVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/mapper/ScheduleMapper.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/ScheduleService.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/ScheduleServiceImpl.java
CNR_FURNITURE/src/main/resources/mybatis/mapper/ScheduleMapper.xml
CNR_FURNITURE/src/main/resources/static/css/workerManagement.css
CNR_FURNITURE/src/main/webapp/WEB-INF/views/process/workerManagement.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/standardInfo/bomInsert.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/standardInfo/materialInfo.jsp

240418 hyunju25: ajax 달력조회

---

CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/MachineInfoController.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/MachineMNGController.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/Machine/MachineCheckRecordVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/Machine/MachineRepairAddVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/Machine/MachineVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/Machine/MachineWorkVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/Machine/SearchMachineVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/mapper/MachineInfoMapper.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/mapper/MachineMNGMapper.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/machine/MachineInfoService.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/machine/MachineInfoServiceImpl.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/machine/MachineMNGService.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/machine/MachineMNGServiceImpl.java
CNR_FURNITURE/src/main/resources/mybatis/mapper/MachineInfoMapper.xml
CNR_FURNITURE/src/main/resources/mybatis/mapper/MachineMNGMapper.xml
CNR_FURNITURE/src/main/webapp/WEB-INF/views/machine/machineInfo.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/machine/machineManagement.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/machine/machineOperationStatus.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/machine/machineRepair.jsp

240419 daeun06 machine 완료

---

CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/scheduler/ScheduleVO.java
CNR_FURNITURE/src/main/resources/mybatis/mapper/ScheduleMapper.xml
CNR_FURNITURE/src/main/resources/static/css/workerManagement.css
CNR_FURNITURE/src/main/webapp/WEB-INF/views/process/workerManagement.jsp

240419 hyunju26: ajax 달력조회

---

CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/ProcessController.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/process/ProcessCtVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/mapper/ProcessMapper.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/ProcessService.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/ProcessServiceImpl.java
CNR_FURNITURE/src/main/resources/mybatis/mapper/ProcessMapper.xml
CNR_FURNITURE/src/main/resources/static/css/process.css
CNR_FURNITURE/src/main/resources/static/js/process.js
CNR_FURNITURE/src/main/webapp/WEB-INF/views/process/manufacturingInstruction.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/process/manufacturingPerform.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/process/processInfo.jsp

240419 dahye25 :제조 지시 수정, pdf 수정

240419 dahye25 :제조 지시 수정, pdf 수정

---

CNR_FURNITURE/src/main/resources/static/js/process.js

240419 dahye27 :제조 지시 수정, pdf 완료

240419 dahye27 :제조 지시 수정, pdf 완료

---

CNR_FURNITURE/src/main/resources/static/css/process.css
CNR_FURNITURE/src/main/resources/static/js/process.js
CNR_FURNITURE/src/main/webapp/WEB-INF/views/process/manufacturingInstruction.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/process/manufacturingPerform.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/process/processInfo.jsp

240420 dahye28 :전체 css 수정

---

CNR_FURNITURE/src/main/resources/static/css/workerManagement.css
CNR_FURNITURE/src/main/resources/static/js/itemInfo.js
CNR_FURNITURE/src/main/webapp/WEB-INF/views/process/workerManagement.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/standardInfo/itemInfo.jsp

240420 hyunju27: 제품, 스케줄러 css

---

CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/WorkController.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/work/search/WorkSearchVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/work/search/WorkSelectEmpInfoVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/work/search/WorkSelectMachineInfoVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/work/search/WorkSelectProcessInfoVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/work/search/WorkSelectWorkVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/work/workMNG/WorkInsertMaterialModalVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/work/workMNG/WorkUpdateMaterialModalVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/work/workerInsert/WorkSelectWorkerVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/mapper/WorkMapper.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/WorkService.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/WorkServiceImpl.java
CNR_FURNITURE/src/main/resources/mybatis/mapper/WorkMapper.xml
CNR_FURNITURE/src/main/resources/static/css/work.css
CNR_FURNITURE/src/main/resources/static/js/work.js
CNR_FURNITURE/src/main/webapp/WEB-INF/views/work/todayWorkInsert.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/work/work.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/work/workerInsert.jsp

240420 jihyeonHome 자재투입등록&수정,workerInsert 중간커밋

240420 jihyeonHome 자재투입등록&수정,workerInsert 중간커밋

---

CNR_FURNITURE/src/main/webapp/WEB-INF/views/process/workerManagement.jsp

240421 hyunju28 작업자스케줄러 오류수정

---

CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/MachineInfoController.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/MachineMNGController.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/Machine/MachineAddVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/Machine/MachineCheckRecordVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/Machine/MachineCheckVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/Machine/MachineRepairAddVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/Machine/MachineRepairVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/Machine/MachineVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/Machine/MachineWorkVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/Machine/SearchMachineCheckVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/Machine/SearchMachineVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/mapper/MachineInfoMapper.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/mapper/MachineMNGMapper.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/machine/MachineInfoService.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/machine/MachineInfoServiceImpl.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/machine/MachineMNGService.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/machine/MachineMNGServiceImpl.java
CNR_FURNITURE/src/main/resources/static/css/machine.css
CNR_FURNITURE/src/main/webapp/WEB-INF/views/machine/machineCheck.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/machine/machineCheckInfo.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/machine/machineInfo.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/machine/machineManagement.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/machine/machineOperationStatus.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/machine/machineRepair.jsp

240421 daeun08 machine 완료

---

CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/ProductionController.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/WorkController.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/production/machineOperationStatusByProcess/ex.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/production/productionStatus/ex.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/production/search/ProductionSearchVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/production/search/ProductionSelectCompanyVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/production/search/ProductionSelectInstructionVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/production/search/ProductionSelectItemVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/production/search/ProductionSelectMachineInfoVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/production/search/ProductionSelectProcessInfoVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/work/workMNG/WorkInsertModalVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/mapper/ProductionMapper.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/mapper/WorkMapper.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/ProductionService.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/ProductionServiceImpl.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/WorkServiceImpl.java
CNR_FURNITURE/src/main/resources/mybatis/mapper/ProductionMapper.xml
CNR_FURNITURE/src/main/resources/mybatis/mapper/WorkMapper.xml
CNR_FURNITURE/src/main/resources/static/js/work.js
CNR_FURNITURE/src/main/webapp/WEB-INF/views/production/machineOperationStatusByProcess.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/production/productionStatus.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/work/work.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/work/workerInsert.jsp

240422 jihyeonHome 중간커밋

---

CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/ProcessController.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/mapper/ProcessMapper.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/ProcessService.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/ProcessServiceImpl.java
CNR_FURNITURE/src/main/resources/mybatis/mapper/ProcessMapper.xml
CNR_FURNITURE/src/main/resources/static/css/process.css
CNR_FURNITURE/src/main/resources/static/js/process.js
CNR_FURNITURE/src/main/webapp/WEB-INF/views/process/manufacturingPerform.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/process/processInfo.jsp

240422 dahye29 : CSS 수정 및, 주석 생성 및, PDF 완료

240422 dahye29 : CSS 수정 및, 주석 생성 및, PDF 완료

---

CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/MachineMNGController.java
CNR_FURNITURE/src/main/webapp/WEB-INF/views/machine/machineCheckInfo.jsp

240422 daeun08 machineCheckInfo.jsp 수정 & 완료

240422 daeun08 machineCheckInfo.jsp 수정 & 완료

---

CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/MachineInfoController.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/Machine/MachineRepairVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/Machine/MachineWorkVO.java

240422 daeun10 machine 완료

---

CNR_FURNITURE/src/main/webapp/WEB-INF/views/process/workerManagement.jsp

240422 hyunju29: 구글달력 api연동

---

CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/WorkController.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/mapper/WorkMapper.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/WorkService.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/WorkServiceImpl.java
CNR_FURNITURE/src/main/resources/mybatis/mapper/WorkMapper.xml
CNR_FURNITURE/src/main/resources/static/js/work.js
CNR_FURNITURE/src/main/webapp/WEB-INF/views/includes/footer.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/work/work.jsp

240422 jihyeon01 중간커밋

---

CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/ProcessController.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/domain/process/ProcessCtVO.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/mapper/ProcessMapper.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/ProcessService.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/ProcessServiceImpl.java
CNR_FURNITURE/src/main/resources/mybatis/mapper/ProcessMapper.xml
CNR_FURNITURE/src/main/resources/static/css/process.css
CNR_FURNITURE/src/main/resources/static/js/process.js
CNR_FURNITURE/src/main/webapp/WEB-INF/views/process/manufacturingInstruction.jsp

240422 dahye32 : 제조지시 등록 추가 생성 및 css 수정

240422 dahye32 : 제조지시 등록 추가 생성 및 css 수정

---

CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/WorkController.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/mapper/WorkMapper.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/WorkService.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/WorkServiceImpl.java
CNR_FURNITURE/src/main/resources/mybatis/mapper/WorkMapper.xml
CNR_FURNITURE/src/main/resources/static/js/work.js
CNR_FURNITURE/src/main/webapp/WEB-INF/views/work/work.jsp

240423 jihyeonHome 작업등록 완료

---

CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/ProcessController.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/mapper/ProcessMapper.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/ProcessService.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/service/ProcessServiceImpl.java
CNR_FURNITURE/src/main/resources/static/css/process.css
CNR_FURNITURE/src/main/resources/static/js/process.js
CNR_FURNITURE/src/main/webapp/WEB-INF/views/process/manufacturingPerform.jsp

240423 dahye33 : 제조수행지시 등록 추가 생성 및 css 수정

240423 dahye33 : 제조수행지시 등록 추가 생성 및 css 수정

---

CNR_FURNITURE/src/main/resources/static/js/process.js
CNR_FURNITURE/src/main/webapp/WEB-INF/views/process/manufacturingInstruction.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/process/manufacturingPerform.jsp

240423 dahye35 :제조수행지시, 제조지시 다중insert 테이블 삭제 버튼 추가

240423 dahye35 :제조수행지시, 제조지시 다중insert 테이블 삭제 버튼 추가

---

CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/BomController.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/ItemInfoController.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/MaterialInfoController.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/ScheduleController.java
CNR_FURNITURE/src/main/webapp/WEB-INF/views/includes/header.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/standardInfo/bomInsert.jsp

240423 hyunju31: 권한수정 url

---

CNR_FURNITURE/src/main/webapp/WEB-INF/views/error/403.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/error/404.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/includes/header.jsp

240423 siyeon09: 404,403 에러 수정 및 헤더 링크 수정

240423 siyeon09: 404,403 에러 수정 및 헤더 링크 수정

---

CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/ProcessController.java
CNR_FURNITURE/src/main/resources/static/js/process.js
CNR_FURNITURE/src/main/webapp/WEB-INF/views/process/manufacturingInstruction.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/process/manufacturingPerform.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/process/processInfo.jsp

240423 dahye36 :제조수행지시, 제조지시,공정정보관리 권한 url 추가

240423 dahye36 :제조수행지시, 제조지시,공정정보관리 권한 url 추가

---

CNR_FURNITURE/src/main/java/com/cnr_furniture/config/SecurityConfig.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/config/auth/CustomAuthSuccessHandler.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/MemberController.java

240423 siyeon11: 로그인 후처리

---

CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/ContractController.java

240423 siyeon11: 계약 컨트롤러 수정

---

CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/MachineInfoController.java
CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/MachineMNGController.java
CNR_FURNITURE/src/main/resources/mybatis/mapper/MachineInfoMapper.xml
CNR_FURNITURE/src/main/webapp/WEB-INF/views/machine/machineCheck.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/machine/machineCheckInfo.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/machine/machineInfo.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/machine/machineManagement.jsp

240423 daeun12 machine 권한 완료

---

CNR_FURNITURE/src/main/resources/static/js/itemInfo.js
CNR_FURNITURE/src/main/webapp/WEB-INF/views/standardInfo/bom.jsp

240423 hyunju32: bom, itemInfoJs 수정

240423 hyunju32: bom, itemInfoJs 수정

---

CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/MachineMNGController.java
CNR_FURNITURE/src/main/webapp/WEB-INF/views/machine/machineCheckInfo.jsp

240423 daeun12 machine 권한 최종 완료

240423 daeun12 machine 권한 최종 완료

---

CNR_FURNITURE/src/main/webapp/WEB-INF/views/process/processInfo.jsp

240423 dahye37 : 공정정보관리등록: 설비url 수정

240423 dahye37 : 공정정보관리등록: 설비url 수정

---

CNR_FURNITURE/src/main/resources/mybatis/mapper/quality/InspectionOBMapper.xml
CNR_FURNITURE/src/main/resources/static/js/quality/inspectionOB.js

240424 suha01: 출하검사관리(inspectionOB) 완료, 자재재고조회 필요

240424 suha01: 출하검사관리(inspectionOB) 완료, 자재재고조회 필요

---

CNR_FURNITURE/src/main/java/com/cnr_furniture/controller/quality/InspectionOBController.java
CNR_FURNITURE/src/main/resources/mybatis/mapper/quality/InspectionOBMapper.xml
CNR_FURNITURE/src/main/webapp/WEB-INF/views/quality/inspectionIB.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/quality/inspectionOB.jsp
CNR_FURNITURE/src/main/webapp/WEB-INF/views/quality/inspectionProcess.jsp

240425 suha03(home): 시큐리티에 따른 url 설정완료, 공정검사관리 등록: 손봐야 함. 갑자기 안되네..

240425 suha03(home): 시큐리티에 따른 url 설정완료, 공정검사관리 등록: 손봐야 함. 갑자기 안되네..

---

CNR_FURNITURE/src/main/java/com/cnr_furniture/config/auth/EmailConfig.java

EmailConfig-개인정보 수정
